services:
  ejercicios:
    build: .
    container_name: ejercicios
    ports:
      - "8000:8000"
    volumes:
      - .:/app 
    environment:
      - MONGO_URI=${MONGO_URI}
      - YOUTUBE_API_KEY=${YOUTUBE_API_KEY}
      - GITHUB_TOKEN=${GITHUB_TOKEN}
    networks:
      - microservicios

networks:
  microservicios:
    external: true