services:
  chat:
    build: .
    container_name: chat
    ports:
      - "8030:8030"
    volumes:
      - .:/app 
    environment:
      - MONGO_URI=${MONGO_URI}
      - MONGO_DB=${MONGO_DB}
      - QDRANT_URL=${QDRANT_URL}
      - QDRANT_API_KEY=${QDRANT_API_KEY}
      - QDRANT_COLLECTION=${QDRANT_COLLECTION}
      - REDIS_URL=${REDIS_URL}
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - EMBEDDING_MODEL=${EMBEDDING_MODEL}
      - GEMINI_MODEL=${GEMINI_MODEL}
    networks:
      - microservicios

networks:
  microservicios:
    external: true